/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Aplicacoes;
import Model.Paciente;
import Model.Vacina;
import ModelDAO.AplicacoesDAO;
import ModelDAO.PacienteDAO;
import ModelDAO.VacinaDAO;
import java.sql.Date;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class AplicarVacinaForm extends javax.swing.JFrame {

    Paciente paciente;
    PacienteDAO pacienteDAO = new PacienteDAO();
    Vacina vacina;
    VacinaDAO vdao = new VacinaDAO();
    AplicacoesDAO apDAO = new AplicacoesDAO();

    /**
     * Creates new form AplicarVacinaForm
     */
    public AplicarVacinaForm() {
        initComponents();
        try {
            carregaTabelaVacina();
            carregaTabelaPaciente();
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, "Falha ao carregar Registros!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        cancelarButton = new javax.swing.JPanel();
        cancelarLabel = new javax.swing.JLabel();
        pacientePanel = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        pacienteTextField = new javax.swing.JTextField();
        pacienteLabel = new javax.swing.JLabel();
        cpfPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        cpfLabel = new javax.swing.JLabel();
        cpfTextField1 = new javax.swing.JTextField();
        procurarButton = new javax.swing.JPanel();
        procurarLabel = new javax.swing.JLabel();
        vacinaPanel = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        vacinaLabel = new javax.swing.JLabel();
        vacinaTextField1 = new javax.swing.JTextField();
        PacienteScrollPane = new javax.swing.JScrollPane();
        pacienteTable = new javax.swing.JTable();
        VacinaScrollPane = new javax.swing.JScrollPane();
        vacinasTable = new javax.swing.JTable();
        aplicarButton = new javax.swing.JPanel();
        aplicarLabel = new javax.swing.JLabel();
        procurarButton1 = new javax.swing.JPanel();
        procurarLabel1 = new javax.swing.JLabel();
        idPanel = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        idLabel = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        comentariosPanel = new javax.swing.JPanel();
        comentariosLabel = new javax.swing.JLabel();
        comentariosScrollPane = new javax.swing.JScrollPane();
        comentariosTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(242, 242, 242));
        titleLabel.setText("Aplicar Vacina");
        jPanel1.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));

        cancelarButton.setBackground(new java.awt.Color(229, 90, 90));
        cancelarButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        cancelarLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cancelarLabel.setForeground(new java.awt.Color(247, 247, 247));
        cancelarLabel.setText("Voltar");
        cancelarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout cancelarButtonLayout = new javax.swing.GroupLayout(cancelarButton);
        cancelarButton.setLayout(cancelarButtonLayout);
        cancelarButtonLayout.setHorizontalGroup(
            cancelarButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancelarButtonLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(cancelarLabel)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        cancelarButtonLayout.setVerticalGroup(
            cancelarButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancelarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(cancelarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 50));

        pacientePanel.setBackground(new java.awt.Color(32, 33, 35));
        pacientePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pacientePanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, 350, -1));

        pacienteTextField.setBackground(new java.awt.Color(32, 33, 35));
        pacienteTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pacienteTextField.setForeground(new java.awt.Color(255, 255, 255));
        pacienteTextField.setToolTipText("");
        pacienteTextField.setBorder(null);
        pacienteTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        pacienteTextField.setEnabled(false);
        pacienteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacienteTextFieldActionPerformed(evt);
            }
        });
        pacientePanel.add(pacienteTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 30, 350, 30));

        pacienteLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        pacienteLabel.setForeground(new java.awt.Color(57, 113, 117));
        pacienteLabel.setText("Nome:");
        pacientePanel.add(pacienteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel1.add(pacientePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 330, -1));

        cpfPanel.setBackground(new java.awt.Color(32, 33, 35));
        cpfPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        cpfPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, 350, -1));

        cpfLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cpfLabel.setForeground(new java.awt.Color(57, 113, 117));
        cpfLabel.setText("CPF:");
        cpfPanel.add(cpfLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        cpfTextField1.setBackground(new java.awt.Color(32, 33, 35));
        cpfTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cpfTextField1.setForeground(new java.awt.Color(255, 255, 255));
        cpfTextField1.setToolTipText("");
        cpfTextField1.setBorder(null);
        cpfTextField1.setCaretColor(new java.awt.Color(255, 255, 255));
        cpfTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfTextField1ActionPerformed(evt);
            }
        });
        cpfPanel.add(cpfTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 30, 350, 30));

        jPanel1.add(cpfPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 330, -1));

        procurarButton.setBackground(new java.awt.Color(42, 44, 44));
        procurarButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        procurarLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        procurarLabel.setForeground(new java.awt.Color(57, 113, 117));
        procurarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        procurarLabel.setText("Procurar Paciente");
        procurarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                procurarLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout procurarButtonLayout = new javax.swing.GroupLayout(procurarButton);
        procurarButton.setLayout(procurarButtonLayout);
        procurarButtonLayout.setHorizontalGroup(
            procurarButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, procurarButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(procurarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        procurarButtonLayout.setVerticalGroup(
            procurarButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(procurarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(procurarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 170, 50));

        vacinaPanel.setBackground(new java.awt.Color(32, 33, 35));
        vacinaPanel.setEnabled(false);
        vacinaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        vacinaPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, 350, -1));

        vacinaLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        vacinaLabel.setForeground(new java.awt.Color(57, 113, 117));
        vacinaLabel.setText("Vacina:");
        vacinaPanel.add(vacinaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        vacinaTextField1.setBackground(new java.awt.Color(32, 33, 35));
        vacinaTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vacinaTextField1.setForeground(new java.awt.Color(255, 255, 255));
        vacinaTextField1.setToolTipText("");
        vacinaTextField1.setBorder(null);
        vacinaTextField1.setCaretColor(new java.awt.Color(255, 255, 255));
        vacinaTextField1.setEnabled(false);
        vacinaTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vacinaTextField1ActionPerformed(evt);
            }
        });
        vacinaPanel.add(vacinaTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 350, 30));

        jPanel1.add(vacinaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 330, -1));

        pacienteTable.setForeground(new java.awt.Color(57, 113, 117));
        pacienteTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "CPF", "Cidade", "Bairro"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        pacienteTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        pacienteTable.setFocusable(false);
        pacienteTable.setGridColor(new java.awt.Color(255, 255, 255));
        pacienteTable.setInheritsPopupMenu(true);
        pacienteTable.getTableHeader().setResizingAllowed(false);
        pacienteTable.getTableHeader().setReorderingAllowed(false);
        pacienteTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pacienteTableMouseClicked(evt);
            }
        });
        PacienteScrollPane.setViewportView(pacienteTable);

        jPanel1.add(PacienteScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 510, 210));

        vacinasTable.setForeground(new java.awt.Color(57, 113, 117));
        vacinasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Quantidade", "Lote", "Obsevações"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        vacinasTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        vacinasTable.setFocusable(false);
        vacinasTable.setGridColor(new java.awt.Color(255, 255, 255));
        vacinasTable.setInheritsPopupMenu(true);
        vacinasTable.getTableHeader().setResizingAllowed(false);
        vacinasTable.getTableHeader().setReorderingAllowed(false);
        vacinasTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vacinasTableMouseClicked(evt);
            }
        });
        VacinaScrollPane.setViewportView(vacinasTable);

        jPanel1.add(VacinaScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 540, 210));

        aplicarButton.setBackground(new java.awt.Color(42, 44, 44));
        aplicarButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        aplicarLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        aplicarLabel.setForeground(new java.awt.Color(57, 113, 117));
        aplicarLabel.setText("Aplicar");
        aplicarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aplicarLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout aplicarButtonLayout = new javax.swing.GroupLayout(aplicarButton);
        aplicarButton.setLayout(aplicarButtonLayout);
        aplicarButtonLayout.setHorizontalGroup(
            aplicarButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aplicarButtonLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(aplicarLabel)
                .addGap(31, 31, 31))
        );
        aplicarButtonLayout.setVerticalGroup(
            aplicarButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aplicarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(aplicarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 570, 130, 40));

        procurarButton1.setBackground(new java.awt.Color(42, 44, 44));
        procurarButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        procurarLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        procurarLabel1.setForeground(new java.awt.Color(57, 113, 117));
        procurarLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        procurarLabel1.setText("Procurar Vacina");
        procurarLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                procurarLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout procurarButton1Layout = new javax.swing.GroupLayout(procurarButton1);
        procurarButton1.setLayout(procurarButton1Layout);
        procurarButton1Layout.setHorizontalGroup(
            procurarButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, procurarButton1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(procurarLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );
        procurarButton1Layout.setVerticalGroup(
            procurarButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(procurarLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(procurarButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 200, 170, 50));

        idPanel.setBackground(new java.awt.Color(32, 33, 35));
        idPanel.setEnabled(false);
        idPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        idPanel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, 350, -1));

        idLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        idLabel.setForeground(new java.awt.Color(57, 113, 117));
        idLabel.setText("ID:");
        idPanel.add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        idTextField.setBackground(new java.awt.Color(32, 33, 35));
        idTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idTextField.setForeground(new java.awt.Color(255, 255, 255));
        idTextField.setToolTipText("");
        idTextField.setBorder(null);
        idTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });
        idPanel.add(idTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 350, 30));

        jPanel1.add(idPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 330, -1));

        comentariosPanel.setBackground(new java.awt.Color(32, 33, 35));
        comentariosPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comentariosLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        comentariosLabel.setForeground(new java.awt.Color(57, 113, 117));
        comentariosLabel.setText("Comentários:");
        comentariosPanel.add(comentariosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        comentariosTextArea.setColumns(20);
        comentariosTextArea.setRows(5);
        comentariosScrollPane.setViewportView(comentariosTextArea);

        comentariosPanel.add(comentariosScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 870, 110));

        jPanel1.add(comentariosPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 930, 160));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldActionPerformed

    private void pacienteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacienteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pacienteTextFieldActionPerformed

    private void vacinaTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vacinaTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vacinaTextField1ActionPerformed

    private void cpfTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfTextField1ActionPerformed

    private void cancelarLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarLabelMouseClicked
        // TODO add your handling code here:
        HomeForm frm = new HomeForm();
        frm.setVisible(true);
        this.hide();
    }//GEN-LAST:event_cancelarLabelMouseClicked

    private void pacienteTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pacienteTableMouseClicked
        // TODO add your handling code here:
        int linha = pacienteTable.getSelectedRow();
        if (linha > -1) {
            DefaultTableModel modelo = (DefaultTableModel) pacienteTable.getModel();
            paciente = new Paciente();
            try {
                paciente = pacienteDAO.getOne(Integer.valueOf(modelo.getValueAt(linha, 0).toString()));
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(PacientesForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            pacienteTextField.setText(String.valueOf(paciente.getNome()));
        }

        try {
            carregaTabelaPaciente();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(PacientesForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pacienteTableMouseClicked

    private void procurarLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_procurarLabelMouseClicked
        try {
            carregaTabelaByCpf();
            cpfTextField1.setText("");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(PacientesForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_procurarLabelMouseClicked

    private void vacinasTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vacinasTableMouseClicked
        // TODO add your handling code here:
        int linha = vacinasTable.getSelectedRow();
        if (linha > -1) {
            DefaultTableModel modelo = (DefaultTableModel) vacinasTable.getModel();
            vacina = new Vacina();
            try {
                vacina = vdao.getOne(Integer.valueOf(modelo.getValueAt(linha, 0).toString()));
                carregaTabelaVacina();
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(VacinasForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            vacinaTextField1.setText(vacina.getNome());
        }

    }//GEN-LAST:event_vacinasTableMouseClicked

    private void procurarLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_procurarLabel1MouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            carregaTabelaById();
            idTextField.setText("");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(VacinasForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_procurarLabel1MouseClicked

    private void aplicarLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aplicarLabelMouseClicked
        // TODO add your handling code here:
        Date data = new Date(System.currentTimeMillis());
        Aplicacoes ap = new Aplicacoes(Integer.valueOf(vacina.getId_vacina()), 2, Integer.valueOf(paciente.getId_paciente()), vacina.getNome(), data.toString(), comentariosTextArea.getText());
        try {
            if (!pacienteTextField.getText().isEmpty() || !vacinaTextField1.getText().isEmpty()) {
                apDAO.insert(ap);
                pacienteTextField.setText("");
                vacinaTextField1.setText("");
                JOptionPane.showMessageDialog(null, "Aplicação realizada com sucesso");
            }else{
                JOptionPane.showMessageDialog(null, "Selecione os registros para a aplicação");
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AplicarVacinaForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_aplicarLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplicarVacinaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplicarVacinaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplicarVacinaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplicarVacinaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplicarVacinaForm().setVisible(true);
            }
        });
    }

    private void carregaTabelaPaciente() throws ClassNotFoundException, SQLException {
        DefaultTableModel modelo = (DefaultTableModel) pacienteTable.getModel();
        modelo.setNumRows(0);

        PacienteDAO pacienteDAO = new PacienteDAO();
        for (Paciente p : pacienteDAO.getAll()) {
            modelo.addRow(new Object[]{
                p.getId_paciente(),
                p.getNome(),
                p.getCpf(),
                p.getCidade(),
                p.getData_nasc()
            });
        }
    }

    private void carregaTabelaVacina() throws ClassNotFoundException, SQLException {
        DefaultTableModel modelo = (DefaultTableModel) vacinasTable.getModel();
        modelo.setNumRows(0);
        VacinaDAO vacinaDAO = new VacinaDAO();
        for (Vacina v : vacinaDAO.getAll()) {
            modelo.addRow(new Object[]{
                v.getId_vacina(),
                v.getNome(),
                v.getQuantidade(),
                v.getObservacoes()
            });
        }
    }

    private void carregaTabelaByCpf() throws ClassNotFoundException, SQLException {
        DefaultTableModel modelo = (DefaultTableModel) pacienteTable.getModel();
        modelo.setNumRows(0);
        PacienteDAO pdao = new PacienteDAO();
        for (Paciente p : pdao.getByCpf(Integer.valueOf(cpfTextField1.getText()))) {
            modelo.addRow(new Object[]{
                p.getId_paciente(),
                p.getNome(),
                p.getCpf(),
                p.getCidade(),
                p.getData_nasc()
            });
        }
    }

    private void carregaTabelaById() throws ClassNotFoundException, SQLException {
        DefaultTableModel modelo = (DefaultTableModel) vacinasTable.getModel();
        modelo.setNumRows(0);
        for (Vacina v : vdao.getById(Integer.valueOf(idTextField.getText()))) {
            modelo.addRow(new Object[]{
                v.getId_vacina(),
                v.getNome(),
                v.getQuantidade(),
                v.getObservacoes()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane PacienteScrollPane;
    private javax.swing.JScrollPane VacinaScrollPane;
    private javax.swing.JPanel aplicarButton;
    private javax.swing.JLabel aplicarLabel;
    private javax.swing.JPanel cancelarButton;
    private javax.swing.JLabel cancelarLabel;
    private javax.swing.JLabel comentariosLabel;
    private javax.swing.JPanel comentariosPanel;
    private javax.swing.JScrollPane comentariosScrollPane;
    private javax.swing.JTextArea comentariosTextArea;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JPanel cpfPanel;
    private javax.swing.JTextField cpfTextField1;
    private javax.swing.JLabel idLabel;
    private javax.swing.JPanel idPanel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel pacienteLabel;
    private javax.swing.JPanel pacientePanel;
    private javax.swing.JTable pacienteTable;
    private javax.swing.JTextField pacienteTextField;
    private javax.swing.JPanel procurarButton;
    private javax.swing.JPanel procurarButton1;
    private javax.swing.JLabel procurarLabel;
    private javax.swing.JLabel procurarLabel1;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel vacinaLabel;
    private javax.swing.JPanel vacinaPanel;
    private javax.swing.JTextField vacinaTextField1;
    private javax.swing.JTable vacinasTable;
    // End of variables declaration//GEN-END:variables
}
