/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Helper.CurrentUser;
import java.awt.Color;
import javax.swing.JPanel;

public class HomeForm extends javax.swing.JFrame {

    /**
     * Creates new form HomeForm
     */
     
    
    public HomeForm() {
        initComponents();
        usernameLabel.setText(CurrentUser.user);
        openPanel = menuPrincipalPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPrincipalPanel = new javax.swing.JPanel();
        pacienteButton = new javax.swing.JPanel();
        pacienteLabel = new javax.swing.JLabel();
        vacinaButton = new javax.swing.JPanel();
        vacinaLabel = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        aplicarButton = new javax.swing.JPanel();
        aplicarLabel = new javax.swing.JLabel();
        sidePanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        pacienteSidePanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        panelTitle = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        sairButton = new javax.swing.JPanel();
        sairLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuPrincipalPanel.setBackground(new java.awt.Color(32, 33, 35));
        menuPrincipalPanel.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        menuPrincipalPanel.setEnabled(false);

        pacienteButton.setBackground(new java.awt.Color(42, 44, 44));
        pacienteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickPaciente(evt);
            }
        });

        pacienteLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        pacienteLabel.setForeground(new java.awt.Color(57, 113, 117));
        pacienteLabel.setText("Paciente");

        javax.swing.GroupLayout pacienteButtonLayout = new javax.swing.GroupLayout(pacienteButton);
        pacienteButton.setLayout(pacienteButtonLayout);
        pacienteButtonLayout.setHorizontalGroup(
            pacienteButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
            .addGroup(pacienteButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pacienteButtonLayout.createSequentialGroup()
                    .addGap(0, 69, Short.MAX_VALUE)
                    .addComponent(pacienteLabel)
                    .addGap(0, 70, Short.MAX_VALUE)))
        );
        pacienteButtonLayout.setVerticalGroup(
            pacienteButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
            .addGroup(pacienteButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pacienteButtonLayout.createSequentialGroup()
                    .addGap(0, 44, Short.MAX_VALUE)
                    .addComponent(pacienteLabel)
                    .addGap(0, 44, Short.MAX_VALUE)))
        );

        vacinaButton.setBackground(new java.awt.Color(42, 44, 44));
        vacinaButton.setPreferredSize(new java.awt.Dimension(260, 142));

        vacinaLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        vacinaLabel.setForeground(new java.awt.Color(57, 113, 117));
        vacinaLabel.setText("Vacina");
        vacinaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickVacina(evt);
            }
        });

        javax.swing.GroupLayout vacinaButtonLayout = new javax.swing.GroupLayout(vacinaButton);
        vacinaButton.setLayout(vacinaButtonLayout);
        vacinaButtonLayout.setHorizontalGroup(
            vacinaButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
            .addGroup(vacinaButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(vacinaButtonLayout.createSequentialGroup()
                    .addGap(0, 69, Short.MAX_VALUE)
                    .addComponent(vacinaLabel)
                    .addGap(0, 70, Short.MAX_VALUE)))
        );
        vacinaButtonLayout.setVerticalGroup(
            vacinaButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
            .addGroup(vacinaButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(vacinaButtonLayout.createSequentialGroup()
                    .addGap(0, 52, Short.MAX_VALUE)
                    .addComponent(vacinaLabel)
                    .addGap(0, 53, Short.MAX_VALUE)))
        );

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        aplicarButton.setBackground(new java.awt.Color(42, 44, 44));
        aplicarButton.setPreferredSize(new java.awt.Dimension(260, 142));

        aplicarLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        aplicarLabel.setForeground(new java.awt.Color(57, 113, 117));
        aplicarLabel.setText("Aplicar vacina");
        aplicarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aplicarLabelclickVacina(evt);
            }
        });

        javax.swing.GroupLayout aplicarButtonLayout = new javax.swing.GroupLayout(aplicarButton);
        aplicarButton.setLayout(aplicarButtonLayout);
        aplicarButtonLayout.setHorizontalGroup(
            aplicarButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
            .addGroup(aplicarButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(aplicarButtonLayout.createSequentialGroup()
                    .addGap(0, 69, Short.MAX_VALUE)
                    .addComponent(aplicarLabel)
                    .addGap(0, 70, Short.MAX_VALUE)))
        );
        aplicarButtonLayout.setVerticalGroup(
            aplicarButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
            .addGroup(aplicarButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(aplicarButtonLayout.createSequentialGroup()
                    .addGap(0, 52, Short.MAX_VALUE)
                    .addComponent(aplicarLabel)
                    .addGap(0, 53, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout menuPrincipalPanelLayout = new javax.swing.GroupLayout(menuPrincipalPanel);
        menuPrincipalPanel.setLayout(menuPrincipalPanelLayout);
        menuPrincipalPanelLayout.setHorizontalGroup(
            menuPrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPrincipalPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(pacienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(vacinaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(aplicarButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        menuPrincipalPanelLayout.setVerticalGroup(
            menuPrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPrincipalPanelLayout.createSequentialGroup()
                .addComponent(pacienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPrincipalPanelLayout.createSequentialGroup()
                .addComponent(vacinaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(menuPrincipalPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(menuPrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPrincipalPanelLayout.createSequentialGroup()
                            .addComponent(aplicarButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)))
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        getContentPane().add(menuPrincipalPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 970, 260));

        sidePanel.setBackground(new java.awt.Color(21, 22, 22));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        logoLabel.setForeground(new java.awt.Color(57, 113, 117));
        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/seringa2.png"))); // NOI18N
        logoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        logoLabel.setFocusable(false);
        sidePanel.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 440));

        pacienteSidePanel.setBackground(new java.awt.Color(21, 22, 22));
        pacienteSidePanel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        pacienteSidePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pacienteSidePanelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pacienteSidePanelLayout = new javax.swing.GroupLayout(pacienteSidePanel);
        pacienteSidePanel.setLayout(pacienteSidePanelLayout);
        pacienteSidePanelLayout.setHorizontalGroup(
            pacienteSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        pacienteSidePanelLayout.setVerticalGroup(
            pacienteSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        sidePanel.add(pacienteSidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 240, 60));

        getContentPane().add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 460));

        topPanel.setBackground(new java.awt.Color(88, 132, 132));
        topPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTitle.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        panelTitle.setForeground(new java.awt.Color(247, 247, 247));
        panelTitle.setText("Menu Principal");
        topPanel.add(panelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(247, 247, 247));
        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        usernameLabel.setText("username");
        usernameLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        topPanel.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 200, 30));

        sairButton.setBackground(new java.awt.Color(229, 90, 90));
        sairButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                click(evt);
            }
        });

        sairLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sairLabel.setForeground(new java.awt.Color(247, 247, 247));
        sairLabel.setText("Sair");

        javax.swing.GroupLayout sairButtonLayout = new javax.swing.GroupLayout(sairButton);
        sairButton.setLayout(sairButtonLayout);
        sairButtonLayout.setHorizontalGroup(
            sairButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(sairButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(sairButtonLayout.createSequentialGroup()
                    .addGap(0, 35, Short.MAX_VALUE)
                    .addComponent(sairLabel)
                    .addGap(0, 36, Short.MAX_VALUE)))
        );
        sairButtonLayout.setVerticalGroup(
            sairButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(sairButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(sairButtonLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(sairLabel)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        topPanel.add(sairButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, 100, 30));

        getContentPane().add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 970, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    JPanel openPanel = new  JPanel();
    
    private void pacienteSidePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pacienteSidePanelMousePressed

    }//GEN-LAST:event_pacienteSidePanelMousePressed

    private void click(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_click
        LoginForm frm = new LoginForm();
        frm.setVisible(true);
        this.hide();
    }//GEN-LAST:event_click

    private void clickPaciente(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickPaciente
        PacientesForm frm = new PacientesForm();
        frm.setVisible(true);
        this.hide();

    }//GEN-LAST:event_clickPaciente

    private void clickVacina(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickVacina
        VacinasForm frm = new VacinasForm();
        frm.setVisible(true);
        this.hide();

    }//GEN-LAST:event_clickVacina

    private void aplicarLabelclickVacina(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aplicarLabelclickVacina
        // TODO add your handling code here:
        AplicarVacinaForm frm = new AplicarVacinaForm();
        frm.setVisible(true);
        this.hide();
    }//GEN-LAST:event_aplicarLabelclickVacina

    void setColor(JPanel panel)
    {
        panel.setBackground(new Color(42,44,44));
    }
    
    void resetColor(JPanel panel)
    {
        panel.setBackground(new Color(21,22,22));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aplicarButton;
    private javax.swing.JLabel aplicarLabel;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel menuPrincipalPanel;
    private javax.swing.JPanel pacienteButton;
    private javax.swing.JLabel pacienteLabel;
    private javax.swing.JPanel pacienteSidePanel;
    private javax.swing.JLabel panelTitle;
    private javax.swing.JPanel sairButton;
    private javax.swing.JLabel sairLabel;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JPanel vacinaButton;
    private javax.swing.JLabel vacinaLabel;
    // End of variables declaration//GEN-END:variables
}
