/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Aplicacoes;
import Model.Paciente;
import ModelDAO.AplicacoesDAO;
import ModelDAO.PacienteDAO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class PacientesForm extends javax.swing.JFrame {

    Paciente paciente;
    PacienteDAO pacienteDAO = new PacienteDAO();
    int cpf;

    public PacientesForm() {
        initComponents();
        try {
            carregaTabela();
        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(this, "Falha ao carregar Registros!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pacientesLabel = new javax.swing.JLabel();
        procurarCpfPanel = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        procurarCpfFormattedTextField = new javax.swing.JFormattedTextField();
        procurarCpfLabel = new javax.swing.JLabel();
        procurarPacienteButton = new javax.swing.JPanel();
        procurarLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Paciente = new javax.swing.JTable();
        jSeparator8 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        pacienteLabel = new javax.swing.JLabel();
        vacinasLabel = new javax.swing.JLabel();
        cancelarButton = new javax.swing.JPanel();
        cancelarLabel = new javax.swing.JLabel();
        novoButton = new javax.swing.JPanel();
        novoLabel = new javax.swing.JLabel();
        removerButton = new javax.swing.JPanel();
        removerLabel = new javax.swing.JLabel();
        salvarButton = new javax.swing.JPanel();
        salvarLabel = new javax.swing.JLabel();
        idPanel = new javax.swing.JPanel();
        jSeparator9 = new javax.swing.JSeparator();
        idFormattedTextField = new javax.swing.JFormattedTextField();
        idLabel = new javax.swing.JLabel();
        nomePanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        nomeTextField1 = new javax.swing.JTextField();
        nomeLabel1 = new javax.swing.JLabel();
        nascimentoPanel = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        nascimentoLabel = new javax.swing.JLabel();
        nascimentoFormattedTextField = new javax.swing.JTextField();
        cpfPanel = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        cpfLabel = new javax.swing.JLabel();
        cpfFormattedTextField = new javax.swing.JTextField();
        cidadePanel = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        cidadeLabel = new javax.swing.JLabel();
        cidadeTextField = new javax.swing.JTextField();
        ruaPanel = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        ruaTextField = new javax.swing.JTextField();
        ruaLabel = new javax.swing.JLabel();
        complementoPanel = new javax.swing.JPanel();
        jSeparator7 = new javax.swing.JSeparator();
        complementoTextField = new javax.swing.JTextField();
        complementoLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pacientesLabel.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        pacientesLabel.setForeground(new java.awt.Color(242, 242, 242));
        pacientesLabel.setText("Pacientes");
        jPanel1.add(pacientesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        procurarCpfPanel.setBackground(new java.awt.Color(32, 33, 35));
        procurarCpfPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        procurarCpfPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, 280, -1));

        procurarCpfFormattedTextField.setBackground(new java.awt.Color(32, 33, 35));
        procurarCpfFormattedTextField.setBorder(null);
        procurarCpfFormattedTextField.setForeground(new java.awt.Color(255, 255, 255));
        try {
            procurarCpfFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        procurarCpfFormattedTextField.setToolTipText("");
        procurarCpfFormattedTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        procurarCpfFormattedTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        procurarCpfFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procurarCpfFormattedTextFieldActionPerformed(evt);
            }
        });
        procurarCpfPanel.add(procurarCpfFormattedTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 30, 280, 30));

        procurarCpfLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        procurarCpfLabel.setForeground(new java.awt.Color(57, 113, 117));
        procurarCpfLabel.setText("CPF:");
        procurarCpfPanel.add(procurarCpfLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel1.add(procurarCpfPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 300, -1));

        procurarPacienteButton.setBackground(new java.awt.Color(42, 44, 44));
        procurarPacienteButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        procurarLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        procurarLabel.setForeground(new java.awt.Color(57, 113, 117));
        procurarLabel.setText("Procurar Paciente");
        procurarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                procurarLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout procurarPacienteButtonLayout = new javax.swing.GroupLayout(procurarPacienteButton);
        procurarPacienteButton.setLayout(procurarPacienteButtonLayout);
        procurarPacienteButtonLayout.setHorizontalGroup(
            procurarPacienteButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, procurarPacienteButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(procurarLabel)
                .addGap(31, 31, 31))
        );
        procurarPacienteButtonLayout.setVerticalGroup(
            procurarPacienteButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(procurarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(procurarPacienteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 180, 50));

        jTable_Paciente.setForeground(new java.awt.Color(57, 113, 117));
        jTable_Paciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "CPF", "Cidade", "Data de nascimento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_Paciente.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable_Paciente.setFocusable(false);
        jTable_Paciente.setGridColor(new java.awt.Color(255, 255, 255));
        jTable_Paciente.setInheritsPopupMenu(true);
        jTable_Paciente.getTableHeader().setResizingAllowed(false);
        jTable_Paciente.getTableHeader().setReorderingAllowed(false);
        jTable_Paciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_PacienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Paciente);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 480, 350));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 20, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 570, 670));

        jPanel2.setBackground(new java.awt.Color(32, 33, 35));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pacienteLabel.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        pacienteLabel.setForeground(new java.awt.Color(242, 242, 242));
        pacienteLabel.setText("Paciente");
        jPanel2.add(pacienteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        vacinasLabel.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        vacinasLabel.setForeground(new java.awt.Color(242, 242, 242));
        vacinasLabel.setText("Vacinas Aplicadas:");
        jPanel2.add(vacinasLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, -1, -1));

        cancelarButton.setBackground(new java.awt.Color(229, 90, 90));
        cancelarButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cancelarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarButtonMouseClicked(evt);
            }
        });

        cancelarLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cancelarLabel.setForeground(new java.awt.Color(247, 247, 247));
        cancelarLabel.setText("Voltar");

        javax.swing.GroupLayout cancelarButtonLayout = new javax.swing.GroupLayout(cancelarButton);
        cancelarButton.setLayout(cancelarButtonLayout);
        cancelarButtonLayout.setHorizontalGroup(
            cancelarButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancelarButtonLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(cancelarLabel)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        cancelarButtonLayout.setVerticalGroup(
            cancelarButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancelarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.add(cancelarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 120, 50));

        novoButton.setBackground(new java.awt.Color(42, 44, 44));
        novoButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        novoLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        novoLabel.setForeground(new java.awt.Color(57, 113, 117));
        novoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        novoLabel.setText("Novo");
        novoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                novoLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout novoButtonLayout = new javax.swing.GroupLayout(novoButton);
        novoButton.setLayout(novoButtonLayout);
        novoButtonLayout.setHorizontalGroup(
            novoButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, novoButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(novoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        novoButtonLayout.setVerticalGroup(
            novoButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(novoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.add(novoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 610, 130, 50));

        removerButton.setBackground(new java.awt.Color(42, 44, 44));
        removerButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        removerLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        removerLabel.setForeground(new java.awt.Color(57, 113, 117));
        removerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        removerLabel.setText("Remover");
        removerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removerLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout removerButtonLayout = new javax.swing.GroupLayout(removerButton);
        removerButton.setLayout(removerButtonLayout);
        removerButtonLayout.setHorizontalGroup(
            removerButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, removerButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(removerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        removerButtonLayout.setVerticalGroup(
            removerButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(removerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.add(removerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 610, 130, 50));

        salvarButton.setBackground(new java.awt.Color(42, 44, 44));
        salvarButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        salvarLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        salvarLabel.setForeground(new java.awt.Color(57, 113, 117));
        salvarLabel.setText("Salvar");
        salvarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salvarLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout salvarButtonLayout = new javax.swing.GroupLayout(salvarButton);
        salvarButton.setLayout(salvarButtonLayout);
        salvarButtonLayout.setHorizontalGroup(
            salvarButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, salvarButtonLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(salvarLabel)
                .addGap(31, 31, 31))
        );
        salvarButtonLayout.setVerticalGroup(
            salvarButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salvarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.add(salvarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 610, 130, 50));

        idPanel.setBackground(new java.awt.Color(32, 33, 35));
        idPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        idPanel.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, 152, -1));

        idFormattedTextField.setBackground(new java.awt.Color(32, 33, 35));
        idFormattedTextField.setBorder(null);
        idFormattedTextField.setForeground(new java.awt.Color(255, 255, 255));
        idFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        idFormattedTextField.setToolTipText("");
        idFormattedTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        idFormattedTextField.setEnabled(false);
        idFormattedTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFormattedTextFieldActionPerformed(evt);
            }
        });
        idPanel.add(idFormattedTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 30, 150, 30));

        idLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        idLabel.setForeground(new java.awt.Color(57, 113, 117));
        idLabel.setText("ID:");
        idPanel.add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel2.add(idPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 160, -1));

        nomePanel.setBackground(new java.awt.Color(32, 33, 35));
        nomePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        nomePanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, 440, -1));

        nomeTextField1.setBackground(new java.awt.Color(32, 33, 35));
        nomeTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomeTextField1.setForeground(new java.awt.Color(255, 255, 255));
        nomeTextField1.setToolTipText("");
        nomeTextField1.setBorder(null);
        nomeTextField1.setCaretColor(new java.awt.Color(255, 255, 255));
        nomeTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextField1ActionPerformed(evt);
            }
        });
        nomePanel.add(nomeTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 30, 440, 30));

        nomeLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        nomeLabel1.setForeground(new java.awt.Color(57, 113, 117));
        nomeLabel1.setText("Nome completo:");
        nomePanel.add(nomeLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel2.add(nomePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 460, -1));

        nascimentoPanel.setBackground(new java.awt.Color(32, 33, 35));
        nascimentoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        nascimentoPanel.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, 180, -1));

        nascimentoLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        nascimentoLabel.setForeground(new java.awt.Color(57, 113, 117));
        nascimentoLabel.setText("Data de nascimento:");
        nascimentoPanel.add(nascimentoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        nascimentoFormattedTextField.setBackground(new java.awt.Color(32, 33, 35));
        nascimentoFormattedTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nascimentoFormattedTextField.setForeground(new java.awt.Color(255, 255, 255));
        nascimentoFormattedTextField.setToolTipText("");
        nascimentoFormattedTextField.setBorder(null);
        nascimentoFormattedTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        nascimentoFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nascimentoFormattedTextFieldActionPerformed(evt);
            }
        });
        nascimentoPanel.add(nascimentoFormattedTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 180, 30));

        jPanel2.add(nascimentoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 190, -1));

        cpfPanel.setBackground(new java.awt.Color(32, 33, 35));
        cpfPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        cpfPanel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, 152, -1));

        cpfLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cpfLabel.setForeground(new java.awt.Color(57, 113, 117));
        cpfLabel.setText("CPF:");
        cpfPanel.add(cpfLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        cpfFormattedTextField.setBackground(new java.awt.Color(32, 33, 35));
        cpfFormattedTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cpfFormattedTextField.setForeground(new java.awt.Color(255, 255, 255));
        cpfFormattedTextField.setToolTipText("");
        cpfFormattedTextField.setBorder(null);
        cpfFormattedTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        cpfFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfFormattedTextFieldActionPerformed(evt);
            }
        });
        cpfPanel.add(cpfFormattedTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, 30));

        jPanel2.add(cpfPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 160, -1));

        cidadePanel.setBackground(new java.awt.Color(32, 33, 35));
        cidadePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        cidadePanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, 300, -1));

        cidadeLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cidadeLabel.setForeground(new java.awt.Color(57, 113, 117));
        cidadeLabel.setText("Cidade:");
        cidadePanel.add(cidadeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        cidadeTextField.setBackground(new java.awt.Color(32, 33, 35));
        cidadeTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cidadeTextField.setForeground(new java.awt.Color(255, 255, 255));
        cidadeTextField.setToolTipText("");
        cidadeTextField.setBorder(null);
        cidadeTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        cidadeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidadeTextFieldActionPerformed(evt);
            }
        });
        cidadePanel.add(cidadeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 320, 30));

        jPanel2.add(cidadePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 320, -1));

        ruaPanel.setBackground(new java.awt.Color(32, 33, 35));
        ruaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        ruaPanel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, 300, -1));

        ruaTextField.setBackground(new java.awt.Color(32, 33, 35));
        ruaTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ruaTextField.setForeground(new java.awt.Color(255, 255, 255));
        ruaTextField.setToolTipText("");
        ruaTextField.setBorder(null);
        ruaTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        ruaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruaTextFieldActionPerformed(evt);
            }
        });
        ruaPanel.add(ruaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 30, 300, 30));

        ruaLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        ruaLabel.setForeground(new java.awt.Color(57, 113, 117));
        ruaLabel.setText("Rua:");
        ruaPanel.add(ruaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel2.add(ruaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 320, -1));

        complementoPanel.setBackground(new java.awt.Color(32, 33, 35));
        complementoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        complementoPanel.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, 225, -1));

        complementoTextField.setBackground(new java.awt.Color(32, 33, 35));
        complementoTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        complementoTextField.setForeground(new java.awt.Color(255, 255, 255));
        complementoTextField.setToolTipText("");
        complementoTextField.setBorder(null);
        complementoTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        complementoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complementoTextFieldActionPerformed(evt);
            }
        });
        complementoPanel.add(complementoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 30, 225, 30));

        complementoLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        complementoLabel.setForeground(new java.awt.Color(57, 113, 117));
        complementoLabel.setText("Complemento:");
        complementoPanel.add(complementoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel2.add(complementoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 240, -1));

        jTable1.setForeground(new java.awt.Color(57, 113, 117));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome da Vacina", "Data da Aplicação", "Observação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setFocusable(false);
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setInheritsPopupMenu(true);
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 640, 100));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void procurarCpfFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procurarCpfFormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_procurarCpfFormattedTextFieldActionPerformed

    private void nomeTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTextField1ActionPerformed

    private void cidadeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidadeTextFieldActionPerformed

    private void ruaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ruaTextFieldActionPerformed

    private void complementoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complementoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_complementoTextFieldActionPerformed

    private void idFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFormattedTextFieldActionPerformed

    private void jTable_PacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_PacienteMouseClicked
        // TODO add your handling code here:
        int linha = jTable_Paciente.getSelectedRow();
        if (linha > -1) {
            DefaultTableModel modelo = (DefaultTableModel) jTable_Paciente.getModel();
            paciente = new Paciente();
            try {
                paciente = pacienteDAO.getOne(Integer.valueOf(modelo.getValueAt(linha, 0).toString()));
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(PacientesForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            idFormattedTextField.setText(String.valueOf(paciente.getId_paciente()));
            nomeTextField1.setText(paciente.getNome());
            nascimentoFormattedTextField.setText(paciente.getData_nasc());
            cidadeTextField.setText(paciente.getCidade());
            cpfFormattedTextField.setText(String.valueOf(paciente.getCpf()));
            ruaTextField.setText(paciente.getRua());
            complementoTextField.setText(paciente.getComplemento());
        }

        try {
            carregaTabela();
            carregaTabelaAplicacoes(paciente.getId_paciente());
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(PacientesForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable_PacienteMouseClicked

    private void novoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_novoLabelMouseClicked
        // TODO add your handling code here:
        idFormattedTextField.setText("");
        nomeTextField1.setText("");
        nascimentoFormattedTextField.setText("");
        cidadeTextField.setText("");
        cpfFormattedTextField.setText("");
        ruaTextField.setText("");
        complementoTextField.setText("");
        paciente = new Paciente();
    }//GEN-LAST:event_novoLabelMouseClicked

    private void removerLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removerLabelMouseClicked
        // TODO add your handling code here:
        if (idFormattedTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, selecione um registro");
        } else {
            try {
                pacienteDAO.delete(paciente);
                carregaTabela();
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(PacientesForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Registro removido!");
        }
        clearFields();
    }//GEN-LAST:event_removerLabelMouseClicked

    private void salvarLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salvarLabelMouseClicked
        Paciente p = new Paciente(nomeTextField1.getText(), cidadeTextField.getText(), ruaTextField.getText(),
                complementoTextField.getText(), nascimentoFormattedTextField.getText(), cpfFormattedTextField.getText());
        PacienteDAO pdao = new PacienteDAO();
        System.out.println(p.toString());
        try {
            if(cpfFormattedTextField.getText().length() != 11){
                JOptionPane.showMessageDialog(null, "Por favor, preencha um cpf válido!");
            }
            else if (nomeTextField1.getText().isEmpty() || cpfFormattedTextField.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor, preencha os campos corretamente!");
            } else if (idFormattedTextField.getText().isEmpty()) {
                pdao.insert(p);
                JOptionPane.showMessageDialog(null, "Registro salvo!");
                clearFields();
                carregaTabela();
            } else {
                p.setId_paciente(Integer.valueOf(idFormattedTextField.getText()));
                pdao.update(p);
                JOptionPane.showMessageDialog(null, "Registro Atualizado!");
                clearFields();
                carregaTabela();
            } 
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(PacientesForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_salvarLabelMouseClicked

    private void cancelarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarButtonMouseClicked
        // TODO add your handling code here:
        HomeForm frm = new HomeForm();
        frm.setVisible(true);
        this.hide();
    }//GEN-LAST:event_cancelarButtonMouseClicked

    private void procurarLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_procurarLabelMouseClicked
        try {
            // TODO add your handling code here:
            carregaTabelaByCpf();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(PacientesForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_procurarLabelMouseClicked

    private void cpfFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfFormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfFormattedTextFieldActionPerformed

    private void nascimentoFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nascimentoFormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nascimentoFormattedTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PacientesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PacientesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PacientesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PacientesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PacientesForm().setVisible(true);
            }
        });
    }

    private void carregaTabela() throws ClassNotFoundException, SQLException {
        DefaultTableModel modelo = (DefaultTableModel) jTable_Paciente.getModel();
        modelo.setNumRows(0);

        PacienteDAO pacienteDAO = new PacienteDAO();
        for (Paciente p : pacienteDAO.getAll()) {
            System.out.println(p.getData_nasc());
            modelo.addRow(new Object[]{
                p.getId_paciente(),
                p.getNome(),
                p.getCpf(),
                p.getCidade(),
                p.getData_nasc()
            });
        }
    }

    private void carregaTabelaAplicacoes(int id) throws ClassNotFoundException, SQLException {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);

        AplicacoesDAO aplicacoesDAO = new AplicacoesDAO();
        for (Aplicacoes p : aplicacoesDAO.getAllByPaciente(id)) {
            modelo.addRow(new Object[]{
                p.getNomeVacina(),
                p.getData_aplicacao(),
                p.getObservacoes()
            });
        }
    }

    public void clearFields() {
        idFormattedTextField.setText("");
        nomeTextField1.setText("");
        nascimentoFormattedTextField.setText("");
        cidadeTextField.setText("");
        cpfFormattedTextField.setText("");
        ruaTextField.setText("");
        complementoTextField.setText("");
    }

    private void carregaTabelaByCpf() throws ClassNotFoundException, SQLException {
        DefaultTableModel modelo = (DefaultTableModel) jTable_Paciente.getModel();
        modelo.setNumRows(0);
        PacienteDAO pdao = new PacienteDAO();
        for (Paciente p : pdao.getByCpf(Integer.valueOf(procurarCpfFormattedTextField.getText()))) {
            modelo.addRow(new Object[]{
                p.getId_paciente(),
                p.getNome(),
                p.getCpf(),
                p.getCidade(),
                p.getData_nasc()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cancelarButton;
    private javax.swing.JLabel cancelarLabel;
    private javax.swing.JLabel cidadeLabel;
    private javax.swing.JPanel cidadePanel;
    private javax.swing.JTextField cidadeTextField;
    private javax.swing.JLabel complementoLabel;
    private javax.swing.JPanel complementoPanel;
    private javax.swing.JTextField complementoTextField;
    private javax.swing.JTextField cpfFormattedTextField;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JPanel cpfPanel;
    private javax.swing.JFormattedTextField idFormattedTextField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JPanel idPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable_Paciente;
    private javax.swing.JTextField nascimentoFormattedTextField;
    private javax.swing.JLabel nascimentoLabel;
    private javax.swing.JPanel nascimentoPanel;
    private javax.swing.JLabel nomeLabel1;
    private javax.swing.JPanel nomePanel;
    private javax.swing.JTextField nomeTextField1;
    private javax.swing.JPanel novoButton;
    private javax.swing.JLabel novoLabel;
    private javax.swing.JLabel pacienteLabel;
    private javax.swing.JLabel pacientesLabel;
    private javax.swing.JFormattedTextField procurarCpfFormattedTextField;
    private javax.swing.JLabel procurarCpfLabel;
    private javax.swing.JPanel procurarCpfPanel;
    private javax.swing.JLabel procurarLabel;
    private javax.swing.JPanel procurarPacienteButton;
    private javax.swing.JPanel removerButton;
    private javax.swing.JLabel removerLabel;
    private javax.swing.JLabel ruaLabel;
    private javax.swing.JPanel ruaPanel;
    private javax.swing.JTextField ruaTextField;
    private javax.swing.JPanel salvarButton;
    private javax.swing.JLabel salvarLabel;
    private javax.swing.JLabel vacinasLabel;
    // End of variables declaration//GEN-END:variables
}
